const glfw = require('glfw-raub');

const keyNames = {
	[glfw.KEY_BACKSPACE]     : 'Backspace',
	[glfw.KEY_CAPS_LOCK]     : 'CapsLock',
	[glfw.KEY_DELETE]        : 'Delete',
	[glfw.KEY_END]           : 'End',
	[glfw.KEY_ENTER]         : 'Enter',
	[glfw.KEY_ESCAPE]        : 'Escape',
	[glfw.KEY_F1]            : 'F1',
	[glfw.KEY_F2]            : 'F2',
	[glfw.KEY_F3]            : 'F3',
	[glfw.KEY_F4]            : 'F4',
	[glfw.KEY_F5]            : 'F5',
	[glfw.KEY_F6]            : 'F6',
	[glfw.KEY_F7]            : 'F7',
	[glfw.KEY_F8]            : 'F8',
	[glfw.KEY_F9]            : 'F9',
	[glfw.KEY_F10]           : 'F10',
	[glfw.KEY_F11]           : 'F11',
	[glfw.KEY_F12]           : 'F12',
	[glfw.KEY_F13]           : 'F13',
	[glfw.KEY_F14]           : 'F14',
	[glfw.KEY_F15]           : 'F15',
	[glfw.KEY_F16]           : 'F16',
	[glfw.KEY_F17]           : 'F17',
	[glfw.KEY_F18]           : 'F18',
	[glfw.KEY_F19]           : 'F19',
	[glfw.KEY_F20]           : 'F20',
	[glfw.KEY_F21]           : 'F21',
	[glfw.KEY_F22]           : 'F22',
	[glfw.KEY_F23]           : 'F23',
	[glfw.KEY_F24]           : 'F24',
	[glfw.KEY_F25]           : 'F25',
	[glfw.KEY_HOME]          : 'Home',
	[glfw.KEY_INSERT]        : 'Insert',
	[glfw.KEY_KP_ENTER]      : 'Enter',
	[glfw.KEY_KP_DECIMAL]    : 'Delete',
	[glfw.KEY_KP_EQUAL]      : 'Equal',
	[glfw.KEY_LEFT]          : 'ArrowLeft',
	[glfw.KEY_UP]            : 'ArrowUp',
	[glfw.KEY_RIGHT]         : 'ArrowRight',
	[glfw.KEY_DOWN]          : 'ArrowDown',
	[glfw.KEY_LEFT_ALT]      : 'Alt',
	[glfw.KEY_RIGHT_ALT]     : 'Alt',
	[glfw.KEY_LEFT_BRACKET]  : 'LeftBracket',
	[glfw.KEY_RIGHT_BRACKET] : 'RightBracket',
	[glfw.KEY_LEFT_CONTROL]  : 'Control',
	[glfw.KEY_RIGHT_CONTROL] : 'Control',
	[glfw.KEY_LEFT_SHIFT]    : 'Shift',
	[glfw.KEY_RIGHT_SHIFT]   : 'Shift',
	[glfw.KEY_LEFT_SUPER]    : 'Meta',
	[glfw.KEY_RIGHT_SUPER]   : 'Meta',
	[glfw.KEY_MENU]          : 'ContextMenu',
	[glfw.KEY_NUM_LOCK]      : 'NumLock',
	[glfw.KEY_PAGE_UP]       : 'PageUp',
	[glfw.KEY_PAGE_DOWN]     : 'PageDown',
	[glfw.KEY_PAUSE]         : 'Pause',
	[glfw.KEY_PRINT_SCREEN]  : 'PrintScreen',
	[glfw.KEY_SCROLL_LOCK]   : 'ScrollLock',
	[glfw.KEY_SPACE]         : ' ',
	[glfw.KEY_TAB]           : 'Tab',
    'CapsLock'     : [glfw.KEY_CAPS_LOCK],
    'Delete'       : [glfw.KEY_DELETE],
    'End'          : [glfw.KEY_END],
    'Enter'        : [glfw.KEY_ENTER],
    'Escape'       : [glfw.KEY_ESCAPE],
    'F1'           : [glfw.KEY_F1],
    'F2'           : [glfw.KEY_F2],
    'F3'           : [glfw.KEY_F3],
    'F4'           : [glfw.KEY_F4],
    'F5'           : [glfw.KEY_F5],
    'F6'           : [glfw.KEY_F6],
    'F7'           : [glfw.KEY_F7],
    'F8'           : [glfw.KEY_F8],
    'F9'           : [glfw.KEY_F9],
    'F10'          : [glfw.KEY_F10],
    'F11'          : [glfw.KEY_F11],
    'F12'          : [glfw.KEY_F12],
    'F13'          : [glfw.KEY_F13],
    'F14'          : [glfw.KEY_F14],
    'F15'          : [glfw.KEY_F15],
    'F16'          : [glfw.KEY_F16],
    'F17'          : [glfw.KEY_F17],
    'F18'          : [glfw.KEY_F18],
    'F19'          : [glfw.KEY_F19],
    'F20'          : [glfw.KEY_F20],
    'F21'          : [glfw.KEY_F21],
    'F22'          : [glfw.KEY_F22],
    'F23'          : [glfw.KEY_F23],
    'F24'          : [glfw.KEY_F24],
    'F25'          : [glfw.KEY_F25],
    'Home'         : [glfw.KEY_HOME],
    'Insert'       : [glfw.KEY_INSERT],
    'Enter'        : [glfw.KEY_KP_ENTER],
    'Delete'       : [glfw.KEY_KP_DECIMAL],
    'Equal'        : [glfw.KEY_KP_EQUAL],
    'ArrowLeft'    : [glfw.KEY_LEFT],
    'ArrowUp'      : [glfw.KEY_UP],
    'ArrowRight'   : [glfw.KEY_RIGHT],
    'ArrowDown'    : [glfw.KEY_DOWN],
    'Alt'          : [glfw.KEY_LEFT_ALT],
    'Alt'          : [glfw.KEY_RIGHT_ALT],
    'LeftBracket'  : [glfw.KEY_LEFT_BRACKET],
    'RightBracket' : [glfw.KEY_RIGHT_BRACKET],
    'Control'      : [glfw.KEY_LEFT_CONTROL],
    'Control'      : [glfw.KEY_RIGHT_CONTROL],
    'Shift'        : [glfw.KEY_LEFT_SHIFT],
    'Shift'        : [glfw.KEY_RIGHT_SHIFT],
    'Meta'         : [glfw.KEY_LEFT_SUPER],
    'Meta'         : [glfw.KEY_RIGHT_SUPER],
    'ContextMenu'  : [glfw.KEY_MENU],
    'NumLock'      : [glfw.KEY_NUM_LOCK],
    'PageUp'       : [glfw.KEY_PAGE_UP],
    'PageDown'     : [glfw.KEY_PAGE_DOWN],
    'Pause'        : [glfw.KEY_PAUSE],
    'PrintScreen'  : [glfw.KEY_PRINT_SCREEN],
    'ScrollLock'   : [glfw.KEY_SCROLL_LOCK],
    ' '            : [glfw.KEY_SPACE],
    'Tab'          : [glfw.KEY_TAB],
};

const codeNames = Object.assign({}, keyNames, {
	[glfw.KEY_EQUAL]         : 'Equal',
	[glfw.KEY_COMMA]         : 'Comma',
	[glfw.KEY_MINUS]         : 'Minus',
	[glfw.KEY_PERIOD]        : 'Period',
	[glfw.KEY_SEMICOLON]     : 'Semicolon',
	[glfw.KEY_SLASH]         : 'Slash',
	[glfw.KEY_APOSTROPHE]    : 'Apostrophe',
	[glfw.KEY_BACKSLASH]     : 'Backslash',
	[glfw.KEY_SPACE]         : 'Space',
	[glfw.KEY_GRAVE_ACCENT]  : 'Backquote',
	[glfw.KEY_LEFT_ALT]      : 'AltLeft',
	[glfw.KEY_RIGHT_ALT]     : 'AltRight',
	[glfw.KEY_LEFT_CONTROL]  : 'ControlLeft',
	[glfw.KEY_RIGHT_CONTROL] : 'ControlRight',
	[glfw.KEY_LEFT_SHIFT]    : 'ShiftLeft',
	[glfw.KEY_RIGHT_SHIFT]   : 'ShiftRight',
	[glfw.KEY_LEFT_SUPER]    : 'MetaLeft',
	[glfw.KEY_RIGHT_SUPER]   : 'MetaRight',
	[glfw.KEY_LEFT]          : 'ArrowLeft',
	[glfw.KEY_UP]            : 'ArrowUp',
	[glfw.KEY_RIGHT]         : 'ArrowRight',
	[glfw.KEY_DOWN]          : 'ArrowDown',
	[glfw.KEY_0]             : 'Digit0',
	[glfw.KEY_1]             : 'Digit1',
	[glfw.KEY_2]             : 'Digit2',
	[glfw.KEY_3]             : 'Digit3',
	[glfw.KEY_4]             : 'Digit4',
	[glfw.KEY_5]             : 'Digit5',
	[glfw.KEY_6]             : 'Digit6',
	[glfw.KEY_7]             : 'Digit7',
	[glfw.KEY_8]             : 'Digit8',
	[glfw.KEY_9]             : 'Digit9',
	[glfw.KEY_KP_0]          : 'Numpad0',
	[glfw.KEY_KP_1]          : 'Numpad1',
	[glfw.KEY_KP_2]          : 'Numpad2',
	[glfw.KEY_KP_3]          : 'Numpad3',
	[glfw.KEY_KP_4]          : 'Numpad4',
	[glfw.KEY_KP_5]          : 'Numpad5',
	[glfw.KEY_KP_6]          : 'Numpad6',
	[glfw.KEY_KP_7]          : 'Numpad7',
	[glfw.KEY_KP_8]          : 'Numpad8',
	[glfw.KEY_KP_9]          : 'Numpad9',
	[glfw.KEY_KP_ADD]        : 'NumpadAdd',
	[glfw.KEY_KP_DECIMAL]    : 'NumpadDecimal',
	[glfw.KEY_KP_DIVIDE]     : 'NumpadDivide',
	[glfw.KEY_KP_ENTER]      : 'NumpadEnter',
	[glfw.KEY_KP_EQUAL]      : 'Equal',
	[glfw.KEY_KP_MULTIPLY]   : 'NumpadMultiply',
	[glfw.KEY_KP_SUBTRACT]   : 'NumpadSubtract',
    [glfw.KEY_EQUAL]         : 'Equal',
    [glfw.KEY_COMMA]         : 'Comma',
    [glfw.KEY_MINUS]         : 'Minus',
    [glfw.KEY_PERIOD]        : 'Period',
    [glfw.KEY_SEMICOLON]     : 'Semicolon',
    'Equal'          : [glfw.KEY_EQUAL],
    'Comma'          : [glfw.KEY_COMMA],
    'Minus'          : [glfw.KEY_MINUS],
    'Period'         : [glfw.KEY_PERIOD],
    'Semicolon'      : [glfw.KEY_SEMICOLON],
    'Slash'          : [glfw.KEY_SLASH],
    'Apostrophe'     : [glfw.KEY_APOSTROPHE],
    'Backslash'      : [glfw.KEY_BACKSLASH],
    'Space'          : [glfw.KEY_SPACE],
    'Backquote'      : [glfw.KEY_GRAVE_ACCENT],
    'AltLeft'        : [glfw.KEY_LEFT_ALT],
    'AltRight'       : [glfw.KEY_RIGHT_ALT],
    'ControlLeft'    : [glfw.KEY_LEFT_CONTROL],
    'ControlRight'   : [glfw.KEY_RIGHT_CONTROL],
    'ShiftLeft'      : [glfw.KEY_LEFT_SHIFT],
    'ShiftRight'     : [glfw.KEY_RIGHT_SHIFT],
    'MetaLeft'       : [glfw.KEY_LEFT_SUPER],
    'MetaRight'      : [glfw.KEY_RIGHT_SUPER],
    'ArrowLeft'      : [glfw.KEY_LEFT],
    'ArrowUp'        : [glfw.KEY_UP],
    'ArrowRight'     : [glfw.KEY_RIGHT],
    'ArrowDown'      : [glfw.KEY_DOWN],
    'Digit0'         : [glfw.KEY_0],
    'Digit1'         : [glfw.KEY_1],
    'Digit2'         : [glfw.KEY_2],
    'Digit3'         : [glfw.KEY_3],
    'Digit4'         : [glfw.KEY_4],
    'Digit5'         : [glfw.KEY_5],
    'Digit6'         : [glfw.KEY_6],
    'Digit7'         : [glfw.KEY_7],
    'Digit8'         : [glfw.KEY_8],
    'Digit9'         : [glfw.KEY_9],
    'Numpad0'        : [glfw.KEY_KP_0],
    'Numpad1'        : [glfw.KEY_KP_1],
    'Numpad2'        : [glfw.KEY_KP_2],
    'Numpad3'        : [glfw.KEY_KP_3],
    'Numpad4'        : [glfw.KEY_KP_4],
    'Numpad5'        : [glfw.KEY_KP_5],
    'Numpad6'        : [glfw.KEY_KP_6],
    'Numpad7'        : [glfw.KEY_KP_7],
    'Numpad8'        : [glfw.KEY_KP_8],
    'Numpad9'        : [glfw.KEY_KP_9],
    'NumpadAdd'      : [glfw.KEY_KP_ADD],
    'NumpadDecimal'  : [glfw.KEY_KP_DECIMAL],
    'NumpadDivide'   : [glfw.KEY_KP_DIVIDE],
    'NumpadEnter'    : [glfw.KEY_KP_ENTER],
    'Equal'          : [glfw.KEY_KP_EQUAL],
    'NumpadMultiply' : [glfw.KEY_KP_MULTIPLY],
    'NumpadSubtract' : [glfw.KEY_KP_SUBTRACT],
});

const letters = {
    "65": "A",
    "66": "B",
    "67": "C",
    "68": "D",
    "69": "E",
    "70": "F",
    "71": "G",
    "72": "H",
    "73": "I",
    "74": "J",
    "75": "K",
    "76": "L",
    "77": "M",
    "78": "N",
    "79": "O",
    "80": "P",
    "81": "Q",
    "82": "R",
    "83": "S",
    "84": "T",
    "85": "U",
    "86": "V",
    "87": "W",
    "88": "X",
    "89": "Y",
    "90": "Z",
    "Q": "81",
    "W": "87",
    "E": "69",
    "R": "82",
    "T": "84",
    "Y": "89",
    "U": "85",
    "I": "73",
    "O": "79",
    "P": "80",
    "A": "65",
    "S": "83",
    "D": "68",
    "F": "70",
    "G": "71",
    "H": "72",
    "J": "74",
    "K": "75",
    "L": "76",
    "Z": "90",
    "X": "88",
    "C": "67",
    "V": "86",
    "B": "66",
    "N": "78",
    "M": "77"
}
module.exports.keyNames = { ...keyNames, ...letters };
module.exports.codeNames = { ...codeNames, ...letters };